### ISSUE TITLE
Replace default export with named export?

### ISSUE THREAD

**Issue by ThiefMaster** [indico/react-overridable#4]
IMHO it's a bit confusing to have both a default export and named exports in a package. Should we make `Overridable` itself also a named export?

**Comment by ntarocco** [comment]
Well this is a breaking change :( and we just released everything :)
I kept as it was in Indico, I actually find nice that the default is the `main` component, the main feature.
Do you see any other pros/cons?

**Comment by ThiefMaster** [comment]
Within `0.0.x` breaking changes are ok ;) FWIW I'd have to update the imports in indico as well.

But if you have an actual release depending on this, let's close this issue. It's not that important anyway.

**Comment by mvidalgarcia** [comment]
Out of curiosity, is there any advantage on using named export?

**Comment by ThiefMaster** [comment]
There are people who think default exports are a bad thing in general, because you lose control over the name it's imported as. If you `export default () => ...` that's a function with no defined name, so it's not even searchable. But here we don't have that problem..

**Comment by ntarocco** [comment]
We can change our integration too. So if you prefer, it is not a big change on our side, better now than later.
